database:
  type: sqlite
  mysql:
    host: "localhost"
    port: 3306
    database: "velocityutils"
    username: "root"
    password: ""

alert:
  enabled: true
  prefix: "&7[&b&lSERVER&7]"
motd:
  enabled: true
  line1: "&aWelcome to this Velocity Server!"
  line2: "<bold><gradient:yellow:green>Enjoy your stay</gradient></bold>"
maintenance:
  enabled: true
  active: false
  motd:
    line1: "&cServer under maintenance!"
    line2: "<bold><gradient:red:yellow>Try again later</gradient></bold>"
  allowed:
    - "Rexigamer666"
report:
  enabled: true
  teleport_on_click: true
  message:
    - "&f-----------------------------"
    - "&eNew Report from {player}!"
    - "&fReported: &c{reported}"
    - "&fReason: &b{reason}"
    - "&fServer: &b{server}"
    - "&eClick to teleport"
    - "&f-----------------------------"
  discord_hook:
    enabled: false
    url: "https://discord.com/api/webhooks/xxxxxxxx/yyyyyyyyyyyy"
    avatar: 'https://www.spigotmc.org/data/resource_icons/123/123517.jpg?1742847968'
    username: 'VelocityUtils'
    color_rgb: "240,43,20"
    title: '📢User Report📢'
    message: |
      📢 **New Report from {reporter}**
      👤 **Reported:** {reported}
      📄 **Reason:** {reason}
      🌍 **Server:** {server}
helpop:
  enabled: true
  teleport_on_click: true
  message:
    - "&f-----------------------------"
    - "&eNew Help Request from {player}!"
    - "&fReason: &b{reason}"
    - "&fServer: &b{server}"
    - "&eClick to teleport"
    - "&f-----------------------------"
  discord_hook:
    enabled: false
    url: "https://discord.com/api/webhooks/xxxxxxxx/yyyyyyyyyyyy"
    avatar: 'https://www.spigotmc.org/data/resource_icons/123/123517.jpg?1742847968'
    username: 'VelocityUtils'
    color_rgb: "227,230,14"
    title: '📢Help Request📢'
    message: |
      📢 **New Help Request from {player}**
      📄 **Reason:** {reason}
      🌍 **Server:** {server}
staffchat:
  enabled: true
  discord_hook:
    enabled: false
    url: "https://discord.com/api/webhooks/xxxxxxxx/yyyyyyyyyyyy"
    avatar: 'https://www.spigotmc.org/data/resource_icons/123/123517.jpg?1742847968'
    username: 'VelocityUtils'
    color_rgb: "20,200,240"
    title: '🗨️Staff Chat🗨️'
    message: |
      🗨️ **Staff Chat from {player}**
      🌍 **Server:** {server}
      💬 **Message:** {message}
adminchat:
  enabled: true
  discord_hook:
    enabled: false
    url: "https://discord.com/api/webhooks/xxxxxxxx/yyyyyyyyyyyy"
    avatar: 'https://www.spigotmc.org/data/resource_icons/123/123517.jpg?1742847968'
    username: 'VelocityUtils'
    color_rgb: "196,3,184"
    title: '🗨️Admin Chat🗨️'
    message: |
      🗨️ **Admin Chat from {player}**
      🌍 **Server:** {server}
      💬 **Message:** {message}
stafftime:
  week_start: "MONDAY"
  discord_hook:
    enabled: false
    join:
      enabled: true
      url: "https://discord.com/api/webhooks/xxxxxxxx/yyyyyyyyyyyy"
      avatar: 'https://www.spigotmc.org/data/resource_icons/123/123517.jpg?1742847968'
      username: 'VelocityUtils'
      color_rgb: "45,255,0"
      title: '🕒Staff Join🕒'
      message: |
          🕒 **{player}** joined the server
    change:
      enabled: true
      url: "https://discord.com/api/webhooks/xxxxxxxx/yyyyyyyyyyyy"
      avatar: 'https://www.spigotmc.org/data/resource_icons/123/123517.jpg?1742847968'
      username: 'VelocityUtils'
      color_rgb: "255,255,0"
      title: '🕒Staff Change🕒'
      message: |
        🕒 **{player}** changed the server
        📋 {from} > {to}
    leave:
      enabled: true
      url: "https://discord.com/api/webhooks/xxxxxxxx/yyyyyyyyyyyy"
      avatar: 'https://www.spigotmc.org/data/resource_icons/123/123517.jpg?1742847968'
      username: 'VelocityUtils'
      color_rgb: "255,0,0"
      title: '🕒Staff Leave🕒'
      message: |
        🕒 **{player}** left the server
        📅 Time today: {time_daily}
        📅 Time this week: {time_weekly}
        📅 Time this month: {time_monthly}
        📋 {time} this session
        🖊️ Servers this session:
        {serverstime}
      serverstime: "- {server} - {time}"
  command:
    enabled: true
    no_type:
      - "&f-----------------------------"
      - "&eStaff Time from {player}"
      - "&fToday: &b{day}"
      - "&fWeek: &b{week}"
      - "&fMonth: &b{month}"
      - "&f-----------------------------"
    type:
      - "&f-----------------------------"
      - "&eStaff Time from {player} ({type})"
      - "&f{type}: &b{time}"
      - "&f-----------------------------"
    day: "Day"
    week: "Week"
    month: "Month"
vlist:
  enabled: true
  default_mode: "server"
  server:
    message:
      - "&f-----------------------------"
      - "&eThere are {count} players online"
      - "{servercount}"
      - "&f-----------------------------"
    servercount: "&7[&b{server} &7(&b{count}&7)] - &f{players}"
  rank:
    message:
      - "&f-----------------------------"
      - "&eThere are {count} players online"
      - "{rankcount}"
      - "&f-----------------------------"
    rankcount: "&7[&b{rank} &7(&b{count}&7)] - &f{players}"
movecommands:
  enabled: true
  lobby:
    server:
      - lobby1
      - lobby2
    message: "&aYou have been moved to a &blobby"
  survival:
    server:
      - survival
    message: "&aYou have been moved to the &dsurvival"
messagescommands:
  enabled: true
  discord:
    message:
      - "&f-----------------------------"
      - "&fJoin ur &9discord"
      - "&9https://discord.com/invite/a3zkKtrjTr"
      - "&f-----------------------------"
    click_action: "OPEN_URL"
    action: https://discord.com/invite/a3zkKtrjTr
    hover: "&9Click to join ur discord"
  newgamemode:
    message:
      - '&f-----------------------------'
      - '&6New Game Mode released'
      - '&#c3d600&lJ&#c6c900&lO&#cabd00&lI&#cdb000&lN &#d1a400&lT&#d49700&lH&#d78a00&lE
              &#db7e00&lN&#de7100&lE&#e26500&lW &#e55800&lS&#e94c00&lU&#ec3f00&lR&#ef3200&lV&#f32600&lI&#f61900&lV&#fa0d00&lA&#fd0000&lL'
      - '&f-----------------------------'
    click_action: "RUN_COMMAND"
    action: "/survival"
    hover: "&6Click to join ur new survival"
  rules:
    message:
      - '&f-----------------------------'
      - '&6Remember to read all the server rules'
      - '&f-----------------------------'
    click_action: "NONE"
find:
  enabled: true
goto:
  enabled: true
stafflist:
  enabled: true
staffjoin:
  enabled: true
  join_message: "&b&lStaff - &a{rank} {player} has joined the server"
  leave_message: "&b&lStaff - &c{rank} {player} has left the server"
  change_message: "&b&lStaff - &e{rank} {player} has changed the server &b{from} &e> &b{server}"
stream:
  enabled: true
  message: "&7[&d&lSTREAM&7] {rank} &b{player} &fis now streaming &b{url}"
  hover_enabled: true
  hover: "&bClick to watch the stream"
  cooldown_seconds: 300
  whitelist: true
  whitelist_links:
    - "https://www.twitch.tv/"
    - "https://www.youtube.com/"
    - "https://www.kick.com/"
serverexecute:
  enabled: true
togglesc:
  enabled: true

messages:
  no_permission: "&cYou don't have permission to use this command"
  no_console: "&cOnly players can use this command"
  new_version_available: "&cA new version of VelocityUtils is available (&b{version}&c)! &e{url}"
  alert_usage: "&cUsage: /alert <message>"
  configuration_reloaded: "&aConfiguration reloaded successfully! For some changes to take effect, you may need to restart the proxy."
  velocityutils_usage: "&cUsage: /velocityutils reload"
  maintenance_not_on_list: "&cThe server is under maintenance!"
  maintenance_usage: "&cUsage: /maintenance <on|off> | /maintenance <add|remove> <nick>"
  maintenance_activated: "&aMaintenance mode activated."
  maintenance_deactivated: "&cMaintenance mode deactivated."
  maintenance_already_on_list: "&cThe player is already in the maintenance list."
  maintenance_player_added: "&aPlayer {player} added to the maintenance list."
  maintenance_player_not_on_list: "&cThe player is not in the maintenance list."
  maintenance_player_removed: "&cPlayer {player} removed from the maintenance list."
  report_usage: "&cUsage: /report <nick> <reason>"
  report_player_not_found: "&cPlayer {player} not found"
  report_sent: "&aYour report for the player {target} was sent"
  report_hover: "&bClick to teleport"
  report_cooldown: "&cYou have {time}s before using /report again"
  report_webhook_error: "&cError trying to send discord report webhook"
  helpop_usage: "&cUsage: /helpop <reason>"
  helpop_cooldown: "&cYou have {time}s before using /helpop again"
  helpop_hover: "&bClick to teleport"
  helpop_sent: "&aYour help request was sent"
  goto_usage: "&cUsage: /goto <player>"
  goto_player_not_found: "&cPlayer {player} not found"
  goto_server_not_found: "&cServer could not be found"
  goto_same_server: "&cYou are currently on the same server as {player}"
  goto_connecting: "&aConnecting with {player} server"
  find_usage: "&cUsage: /find <player>"
  find_player_not_found: "&cPlayer {player} not found"
  find_where: "&b{player} &eis on &b{server}"
  find_last_seen: "&e{player} &cis not connected. Last seen: &e{time} ago"
  find_less_minute: "Less than 1 minute"
  server_unknown: "Unknown"
  stafflist_no_staff: "&cThere are no staff online"
  stafflist_header: "&b&lStaff List"
  stafflist_staff: "{prefix} &f{player} &7- &b{server}"
  staffchat_disabled: "&eStaff chat &cdisabled"
  staffchat_enabled: "&eStaff chat &aenabled"
  staffchat_format: "&8[&bStaffChat&8] &7{server} - {prefix} &b{player}&7: &f{message}"
  adminchat_disabled: "&eAdmin chat &cdisabled"
  adminchat_enabled: "&eAdmin chat &aenabled"
  adminchat_format: "&8[&dAdminChat&8] &7{server} - {prefix} &d{player}&7: &f{message}"
  stafftime_usage: "&cUsage: /stafftime <player> [day|week|month]"
  stafftime_not_found: "&cPlayer {player} not found on the database."
  stafftime_invalid_type: "&cInvalid type. Use day, week or month"
  vlist_no_players: "&cThere are no players online."
  movecommands_no_servers: "&cThere are no servers configured for this command"
  movecommands_server_not_found: "&cThat server is not available at this moment."
  movecommands_already_connected: "&cYou are already connected to that server"
  messagescommands_no_message_console: "&cThe messagecommand message is empty: {command}"
  messagescommands_no_action_or_hover_console: "&cThe messagecommand {command} has action set to true, but no action or hover set"
  messagescommands_error_player: "&cThat messagecommand doesnt work as intended, contact an administrator"
  stream_usage: "&cUsage: /stream <url>"
  stream_invalid_url: "&cThats not a valid stream url"
  stream_cooldown: "&cYou have to wait {cooldown} before using /stream again"
  serverexecute_usage: "&cUsage: /serverexecute <server> <command>"
  serverexecute_server_not_found: "&cServer {server} not found"
  serverexecute_sent: "&aSent to server {server}, the command: /{command}"
  togglesc_enabled: "&aStaff chat messages will be shown"
  togglesc_disabled: "&cStaff chat messages will be hidden"
  day_simbol: "d"
  hour_simbol: "h"
  minute_simbol: "m"
  second_simbol: "s"